// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwztu5tkkZUZUbUXfZkEV7uiEtpYyZ8s',
    appId: '1:322684618364:web:b4c1626fc100a55ffc6bf9',
    messagingSenderId: '322684618364',
    projectId: 'social-app-bc587',
    authDomain: 'social-app-bc587.firebaseapp.com',
    storageBucket: 'social-app-bc587.appspot.com',
    measurementId: 'G-Q9ZQVQ10F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDflI-Y5kj-zpP5boCjE71GjcG6J2iIoZc',
    appId: '1:322684618364:android:e9c1d78369a7c532fc6bf9',
    messagingSenderId: '322684618364',
    projectId: 'social-app-bc587',
    storageBucket: 'social-app-bc587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ci4s79DJN-6VG3syhB12GxRaEBHC4Y8',
    appId: '1:322684618364:ios:1e5e618c5c3a2385fc6bf9',
    messagingSenderId: '322684618364',
    projectId: 'social-app-bc587',
    storageBucket: 'social-app-bc587.appspot.com',
    androidClientId: '322684618364-e94jd0inlkkmr23tbap2ji9eo34mi0cn.apps.googleusercontent.com',
    iosClientId: '322684618364-mdehghbsrr5a5v24hpiisfm1fpefo4a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ci4s79DJN-6VG3syhB12GxRaEBHC4Y8',
    appId: '1:322684618364:ios:e4f2a3f1c4f929acfc6bf9',
    messagingSenderId: '322684618364',
    projectId: 'social-app-bc587',
    storageBucket: 'social-app-bc587.appspot.com',
    androidClientId: '322684618364-e94jd0inlkkmr23tbap2ji9eo34mi0cn.apps.googleusercontent.com',
    iosClientId: '322684618364-hl2eql6rc7pd1f3ipq218pcotd9evlm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
